# Generated by Django 2.2.12 on 2022-10-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
